### ISSUE TITLE
Followcycle doesn't work under pause

### ISSUE THREAD

**Issue by wolf6542** [rtcwmp-com/rtcwPro#253] opened 2021-01-19 12:24 UTC
Reported as: dead client under pause, cannot follow cycle team mates.

**Comment by natelo** [comment] 2021-01-19 12:26
Isn't that a concept of pause?

**Comment by krazykaze81** [comment] 2021-01-19 21:30
Confirmed in release/1.1.2 that during pause you cannot change players, free float spectator, move, or anything - almost like all commands are ignored

**Comment by natelo** [comment] 2021-01-19 21:50
Where does that leave us? Should we tackle this or not?

**Comment by natelo** [comment] 2021-01-20 16:10
As discussed we only addressed Ref. So, Ref can now freely or follow players during pause ..

**Comment by krazykaze81** [comment] 2021-01-28 16:22
Moving from player to player works for Referee, but you cannot go from following a player back to free-floating spectator - it gives the error that you cannot switch teams.  I think we should change this to allow Referee to switch teams if they are a Spectator (i.e. press enter to go to free float spec)

**Comment by natelo** [comment] 2021-02-10 07:40
Since branch was merged already... this has been addressed and solved in feature/misc-fixes branch and will be merged into develop.

**Closed by natelo** 2021-02-10 07:40 UTC
Labels: Ready for testing
